name: SoulJars
version: ${project.version}
author: TheBusyBiscuit
website: https://github.com/TheBusyBiscuit/souljars

api-version: 1.14
main: io.github.thebusybiscuit.souljars.SoulJars

depend:
- Slimefun
